framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            asynch: '%env(RABBITMQ_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
            'App\Message\OrderConfirmationEmail': asynch
